In [1]:
import numpy as np
from matplotlib import pyplot as plt
import torch
import pandas

In [ ]:
def f_act_out(x):
    '''Linear activation function'''
    return x

def f_act_hidden(x):
    '''Sigmoid activation function'''
    return 1/(1+np.exp(-x))

class NeuralNetwork():
    def __init__(self, input, hidden_units, output_units):
        self.input = input
        self.hidden = np.random.random((hidden_units, input.shape[1]))
        self.output = np.random.random((output_units, input.shape[1]))
        self.w_ji = np.random.random((hidden_units, input.shape[0]))
        self.bias_ji = np.random.random((hidden_units, 1))
        self.w_kj = np.random.random((output_units, hidden_units))
        self.bias_kj = np.random.random((output_units, 1))
        #Da mettere i bias
        #Possiamo anche mettere un 1 in capo al vettore input e il bias contarlo nella matrice w.

    def forward_prop(self):

        self.hidden = f_act_hidden(self.w_ji @ self.input + self.bias_ji)  # hidden x N
        self.output = f_act_out(self.w_kj @ self.hidden + self.bias_kj) #+ bias #output x N
    
    def backward_prop(self):
        
        delta_k = (self.output - self.target) * np.gradient(self.output)[1] # output x N
        delta_j = np.sum(delta_k @ self.w_kj)
        Dw_kj = delta_k @ self.hidden.T # output x N @ N x hidden = output x hidden 



In [2]:
N = 100 #dimensione pattern
dim_input = 5 #dimensione input
dim_hl = 3 #dimensione hidden layer
dim_ol = 2 #dimensione output layer

input = np.ones((dim_input,N))
target = np.ones((dim_ol,N))

w_ji = np.ones((dim_hl, dim_input))
w_kj = np.ones((dim_ol, dim_hl))

hidden = np.ones((dim_hl,N))
output = np.ones((dim_ol,N))

def f_act_out(x):
    '''Linear activation function'''
    return x

def f_act_hidden(x):
    '''Sigmoid activation function'''
    return 1/(1+np.exp(-x))

#Forward computation
hidden = f_act_hidden(w_ji @ input)
output = f_act_out(w_kj @ hidden)
print(output.shape)
#print(output)


(2, 100)


In [8]:
a = np.array([[1,2,3,4,5,6],[1,4,9,16,25,36]])
print(a.shape)
np.gradient(a)

(2, 6)


[array([[ 0.,  2.,  6., 12., 20., 30.],
        [ 0.,  2.,  6., 12., 20., 30.]]),
 array([[ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 3.,  4.,  6.,  8., 10., 11.]])]

In [5]:
np.array(np.gradient(output))[1]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [4]:
#Computation of errors at output layer
#print(np.array(np.gradient(output)))
delta_k = (-output+target) * (output)
print(delta_k.shape)
Dw_kj = delta_k @ hidden.T
delta_j = (w_kj.T @ delta_k) * hidden #delta_j deve essere N x input 
Dw_ji = delta_j @ input.T
print(Dw_ji.shape)
print(w_ji.shape)

(2, 100)
(3, 5)
(3, 5)


In [15]:
w_kj.shape

(2, 3)

In [ ]:
def forward_propagation()

In [ ]:
class Layer():
    def __init__(units, act_function):
        self.units = units
        self.act_function = act_function

        self.layer = np.empty((units, 1))
    
    def update_w(Dw)

class NeuralNetwork(Layer):
    def __init__(self, input, hidden_units, output_units):
        self.input = input
        self.hidden = np.random.random((hidden_units, input.shape[1]))
        #self.hidden = Layer(hidden_units, act_function)
        self.output = np.random.random((output_units, input.shape[1]))
        #self.output = Layer(output_units, act_function)

        self.w_ji = np.random.random((hidden_units, input.shape[0]))
        self.bias_ji = np.random.random((hidden_units, 1))

        self.w_kj = np.random.random((output_units, hidden_units))
        self.bias_kj = np.random.random((output_units, 1))
        
        #Da mettere i bias
        #Possiamo anche mettere un 1 in capo al vettore input e il bias contarlo nella matrice w.

    def forward_prop(self):

        self.hidden = f_act_hidden(self.w_ji @ self.input + self.bias_ji)  # hidden x N
        self.output = f_act_out(self.w_kj @ self.hidden + self.bias_kj) #+ bias #output x N
    
    def backward_prop(self):
        
        delta_k = (self.output - self.target) * np.gradient(self.output)[1] # output x N
        delta_j = np.sum(delta_k @ self.w_kj)
        Dw_kj = delta_k @ self.hidden.T # output x N @ N x hidden = output x hidden 


In [36]:
def linear(x):
    '''Linear activation function'''
    return x

def sigmoid(x):
    '''Sigmoid activation function'''
    return 1/(1+np.exp(-x))

def d_sigmoid(x):
    return sigmoid(x)*(1-sigmoid(x))

layers_a = []
layers_z = []
weights = []
biases = []

d_weights = []
d_biases = []

N = 100 #batch dimension
input_dim = 5 
hidden_dim = 8
output_dim = 3
layer_dim = [hidden_dim, output_dim]

for i in range(len(layer_dim)):
    layers_a.append(np.empty((layer_dim[i],N)))
    layers_z.append(np.empty((layer_dim[i],N)))

input = np.random.random((input_dim,N))
y = np.random.randint(0,2,(output_dim,N))

w_ji = np.random.uniform(-0.3,0.3,(hidden_dim,input_dim))
weights.append(w_ji)
d_weights.append(np.empty((hidden_dim,input_dim)))
w_kj = np.random.uniform(-0.3,0.3,(output_dim,hidden_dim))
weights.append(w_kj)
d_weights.append(np.empty((output_dim,hidden_dim)))

b_j = np.ones((hidden_dim,1))
biases.append(b_j)
d_biases.append(np.empty((hidden_dim,1)))
b_k = np.ones((output_dim,1))
biases.append(b_k)
d_biases.append(np.empty((output_dim,1)))

act_functions = [sigmoid, sigmoid]
d_act_functions = [d_sigmoid, d_sigmoid]

#forward propagation
for l in range(len(layer_dim)):
    if l == 0:
        layers_z[l] = weights[l] @ input + biases[l]
        layers_a[l] = act_functions[l](layers_z[l])
    else:
        layers_z[l] = weights[l] @ layers_a[l-1] + biases[l]
        layers_a[l] = act_functions[l](layers_z[l])


In [37]:
for i,a in enumerate(layers_a):
    print(f'Layer {i}')
    print(a.shape)

Layer 0
(8, 100)
Layer 1
(3, 100)


In [38]:
deltas = []
deltas.append(np.empty((hidden_dim,N)))
deltas.append(np.empty((output_dim,N)))
#backpropagation
for l in range(len(layer_dim)-1,-1,-1):
    if l == len(layer_dim)-1:
        deltas[l] = 2*d_act_functions[l](layers_z[l])*(layers_a[l]-y)/y.shape[1]
    else:
        deltas[l] = weights[l+1].T @ deltas[l+1]

for i in range(len(d_weights)):
    if i == 0:
        d_weights[i] = deltas[i] @ input.T
        d_biases[i] = deltas[i].sum(axis=1).reshape((deltas[i].shape[0],1))
    else: 
        d_weights[i] = deltas[i] @ layers_a[i-1].T
        d_biases[i] = deltas[i].sum(axis=1).reshape((deltas[i].shape[0],1))

print(d_weights[0])
print(d_weights[1].shape)
print(d_biases[0].shape)
print(d_biases[1].shape)

[[ 0.00662616  0.00637228  0.00738034  0.00656117  0.00549375]
 [-0.00013578 -0.00017834 -0.00179814 -0.00084971 -0.00219556]
 [ 0.01820403  0.01612615  0.01666229  0.01376057  0.01351528]
 [-0.01185664 -0.01150553 -0.01260115 -0.01173269 -0.0087819 ]
 [-0.00868432 -0.00777199 -0.00681573 -0.00630867 -0.0047521 ]
 [ 0.02431211  0.02184938  0.02301277  0.01932113  0.01832983]
 [-0.0070048  -0.00741169 -0.0090143  -0.00881523 -0.00583896]
 [ 0.02128513  0.01959225  0.02293638  0.01893471  0.01867783]]
(3, 8)
(8, 1)
(3, 1)


In [31]:
layers_a[1]-y

array([[ 0.78905826,  0.78730059,  0.78733309,  0.78616837, -0.20993073,
        -0.21140939,  0.7859117 , -0.21303588, -0.21308077, -0.2135605 ,
        -0.2110439 ,  0.78884225, -0.21158154,  0.78646433,  0.78993787,
        -0.20897614, -0.21609959,  0.78995301,  0.78688812, -0.21136026,
        -0.21391391, -0.21243251,  0.78749986,  0.78812805, -0.2118314 ,
         0.78706355, -0.21128195, -0.2084679 , -0.21369724,  0.78788733,
        -0.21316653,  0.7896671 , -0.21333439, -0.21049669,  0.79088574,
        -0.21172429, -0.21243227, -0.20843329, -0.21146457,  0.78660247,
         0.78800862, -0.21007861, -0.2141437 , -0.21124813,  0.78869404,
         0.78656868, -0.21280227,  0.78493183,  0.7842638 , -0.21332867,
         0.78793858, -0.21308368,  0.78754794,  0.78531495, -0.21404935,
        -0.21315808,  0.78590645, -0.21325774,  0.7872054 , -0.21234994,
        -0.2098902 ,  0.78481456,  0.78308358, -0.21308017, -0.2116251 ,
        -0.21313975, -0.21323762, -0.21489639, -0.2

In [39]:
#weight update
eta = 0.1
for i in range(len(weights)):
    weights[i] = weights[i] - d_weights[i]*eta
    biases[i] = biases[i] - d_biases[i]*eta
    print(weights[i].shape)
    print(biases[i].shape)




(8, 5)
(8, 1)
(3, 8)
(3, 1)


In [41]:
def linear(x):
    '''Linear activation function'''
    return x

def sigmoid(x):
    '''Sigmoid activation function'''
    return 1/(1+np.exp(-x))

def d_sigmoid(x):
    return sigmoid(x)*(1-sigmoid(x))

layers_a = []
layers_z = []
weights = []
biases = []

d_weights = []
d_biases = []

N = 100 #batch dimension
input_dim = 5 
hidden_dim = 8
output_dim = 3
layer_dim = [hidden_dim, output_dim]

for i in range(len(layer_dim)):
    layers_a.append(np.empty((layer_dim[i],N)))
    layers_z.append(np.empty((layer_dim[i],N)))

input = np.random.random((input_dim,N))
y = np.random.randint(0,2,(output_dim,N))

w_ji = np.random.uniform(-0.3,0.3,(hidden_dim,input_dim))
weights.append(w_ji)
d_weights.append(np.empty((hidden_dim,input_dim)))
w_kj = np.random.uniform(-0.3,0.3,(output_dim,hidden_dim))
weights.append(w_kj)
d_weights.append(np.empty((output_dim,hidden_dim)))

b_j = np.ones((hidden_dim,1))
biases.append(b_j)
d_biases.append(np.empty((hidden_dim,1)))
b_k = np.ones((output_dim,1))
biases.append(b_k)
d_biases.append(np.empty((output_dim,1)))

act_functions = [sigmoid, sigmoid]
d_act_functions = [d_sigmoid, d_sigmoid]
o = 0
while o<1000:
    print(f'o = {o}')
    #forward propagation
    for l in range(len(layer_dim)):
        if l == 0:
            layers_z[l] = weights[l] @ input + biases[l]
            layers_a[l] = act_functions[l](layers_z[l])
        else:
            layers_z[l] = weights[l] @ layers_a[l-1] + biases[l]
            layers_a[l] = act_functions[l](layers_z[l])

    deltas = []
    deltas.append(np.empty((hidden_dim,N)))
    deltas.append(np.empty((output_dim,N)))
    #backpropagation
    for l in range(len(layer_dim)-1,-1,-1):
        if l == len(layer_dim)-1:
            deltas[l] = 2*d_act_functions[l](layers_z[l])*(layers_a[l]-y)/y.shape[1]
        else:
            deltas[l] = weights[l+1].T @ deltas[l+1]

    for i in range(len(d_weights)):
        if i == 0:
            d_weights[i] = deltas[i] @ input.T
            d_biases[i] = deltas[i].sum(axis=1).reshape((deltas[i].shape[0],1))
        else: 
            d_weights[i] = deltas[i] @ layers_a[i-1].T
            d_biases[i] = deltas[i].sum(axis=1).reshape((deltas[i].shape[0],1))

    print(d_weights[0])
    print(d_weights[1].shape)
    print(d_biases[0].shape)
    print(d_biases[1].shape)
    #weight update
    eta = 0.1
    for i in range(len(weights)):
        weights[i] = weights[i] - d_weights[i]*eta
        biases[i] = biases[i] - d_biases[i]*eta

    o += 1

o = 0
[[ 6.48660154e-03  8.00734295e-03  7.71131681e-03  8.85992170e-03
   1.53310791e-02]
 [ 1.54963138e-03  9.24433111e-04  9.03558298e-04  1.39018677e-03
  -2.99564875e-03]
 [-5.43718848e-03 -2.04917168e-03 -5.63199973e-03 -4.01042467e-03
  -2.97804525e-03]
 [ 5.34609209e-05 -2.29183491e-03 -5.36279278e-04 -1.65494845e-03
  -5.93937491e-03]
 [-1.87564931e-02 -1.88874266e-02 -1.88858419e-02 -2.24856977e-02
  -1.94221400e-02]
 [ 2.37262682e-02  2.25031735e-02  2.40921910e-02  2.74274370e-02
   2.43228681e-02]
 [-1.78906341e-03 -2.62458350e-03 -3.00558463e-03 -2.75081735e-03
  -9.92729603e-03]
 [-5.87150271e-03 -2.94580727e-03 -6.09520404e-03 -4.86742405e-03
  -4.06468689e-03]]
(3, 8)
(8, 1)
(3, 1)
o = 1
[[ 0.0053944   0.00701504  0.00659632  0.00769322  0.01440388]
 [ 0.00099607  0.00039569  0.0003271   0.00073289 -0.00369641]
 [-0.00587226 -0.00237295 -0.00606357 -0.00450102 -0.00337306]
 [-0.00066144 -0.00300866 -0.00127615 -0.00252492 -0.00685863]
 [-0.01934249 -0.01941786 -0.01944