In [1]:
import numpy as np
from matplotlib import pyplot as plt
import torch
import pandas

In [ ]:
def f_act_out(x):
    '''Linear activation function'''
    return x

def f_act_hidden(x):
    '''Sigmoid activation function'''
    return 1/(1+np.exp(-x))

class NeuralNetwork():
    def __init__(self, input, hidden_units, output_units):
        self.input = input
        self.hidden = np.random.random((hidden_units, input.shape[1]))
        self.output = np.random.random((output_units, input.shape[1]))
        self.w_ji = np.random.random((hidden_units, input.shape[0]))
        self.bias_ji = np.random.random((hidden_units, 1))
        self.w_kj = np.random.random((output_units, hidden_units))
        self.bias_kj = np.random.random((output_units, 1))
        #Da mettere i bias
        #Possiamo anche mettere un 1 in capo al vettore input e il bias contarlo nella matrice w.

    def forward_prop(self):

        self.hidden = f_act_hidden(self.w_ji @ self.input + self.bias_ji)  # hidden x N
        self.output = f_act_out(self.w_kj @ self.hidden + self.bias_kj) #+ bias #output x N
    
    def backward_prop(self):
        
        delta_k = (self.output - self.target) * np.gradient(self.output)[1] # output x N
        delta_j = np.sum(delta_k @ self.w_kj)
        Dw_kj = delta_k @ self.hidden.T # output x N @ N x hidden = output x hidden 



In [2]:
N = 100 #dimensione pattern
dim_input = 5 #dimensione input
dim_hl = 3 #dimensione hidden layer
dim_ol = 2 #dimensione output layer

input = np.ones((dim_input,N))
target = np.ones((dim_ol,N))

w_ji = np.ones((dim_hl, dim_input))
w_kj = np.ones((dim_ol, dim_hl))

hidden = np.ones((dim_hl,N))
output = np.ones((dim_ol,N))

def f_act_out(x):
    '''Linear activation function'''
    return x

def f_act_hidden(x):
    '''Sigmoid activation function'''
    return 1/(1+np.exp(-x))

#Forward computation
hidden = f_act_hidden(w_ji @ input)
output = f_act_out(w_kj @ hidden)
print(output.shape)
#print(output)


(2, 100)


In [8]:
a = np.array([[1,2,3,4,5,6],[1,4,9,16,25,36]])
print(a.shape)
np.gradient(a)

(2, 6)


[array([[ 0.,  2.,  6., 12., 20., 30.],
        [ 0.,  2.,  6., 12., 20., 30.]]),
 array([[ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 3.,  4.,  6.,  8., 10., 11.]])]

In [5]:
np.array(np.gradient(output))[1]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [4]:
#Computation of errors at output layer
#print(np.array(np.gradient(output)))
delta_k = (-output+target) * (output)
print(delta_k.shape)
Dw_kj = delta_k @ hidden.T
delta_j = (w_kj.T @ delta_k) * hidden #delta_j deve essere N x input 
Dw_ji = delta_j @ input.T
print(Dw_ji.shape)
print(w_ji.shape)

    


(2, 100)
(3, 5)
(3, 5)


In [15]:
w_kj.shape

(2, 3)

In [ ]:
def forward_propagation()

In [ ]:
class Layer():
    def __init__(units, act_function):
        self.units = units
        self.act_function = act_function

        self.layer = np.empty((units, 1))
    
    def update_w(Dw)

class NeuralNetwork(Layer):
    def __init__(self, input, hidden_units, output_units):
        self.input = input
        self.hidden = np.random.random((hidden_units, input.shape[1]))
        #self.hidden = Layer(hidden_units, act_function)
        self.output = np.random.random((output_units, input.shape[1]))
        #self.output = Layer(output_units, act_function)

        self.w_ji = np.random.random((hidden_units, input.shape[0]))
        self.bias_ji = np.random.random((hidden_units, 1))

        self.w_kj = np.random.random((output_units, hidden_units))
        self.bias_kj = np.random.random((output_units, 1))
        
        #Da mettere i bias
        #Possiamo anche mettere un 1 in capo al vettore input e il bias contarlo nella matrice w.

    def forward_prop(self):

        self.hidden = f_act_hidden(self.w_ji @ self.input + self.bias_ji)  # hidden x N
        self.output = f_act_out(self.w_kj @ self.hidden + self.bias_kj) #+ bias #output x N
    
    def backward_prop(self):
        
        delta_k = (self.output - self.target) * np.gradient(self.output)[1] # output x N
        delta_j = np.sum(delta_k @ self.w_kj)
        Dw_kj = delta_k @ self.hidden.T # output x N @ N x hidden = output x hidden 


In [11]:
def linear(x):
    '''Linear activation function'''
    return x

def sigmoid(x):
    '''Sigmoid activation function'''
    return 1/(1+np.exp(-x))

def d_sigmoid(x):
    return sigmoid(x)*(1-sigmoid(x))

layers_a = []
layers_z = []
weights = []
biases = []

d_weights = []
d_biases = []

N = 100 #batch dimension
input_dim = 5 
hidden_dim = 8
output_dim = 3
layer_dim = [hidden_dim, output_dim]

for i in range(len(layer_dim)):
    layers_a.append(np.empty((layer_dim[i],N)))
    layers_z.append(np.empty((layer_dim[i],N)))

input = np.random.random((input_dim,N))
y = np.random.randint(0,2,(output_dim,N))

w_ji = np.random.uniform(-0.3,0.3,(hidden_dim,input_dim))
weights.append(w_ji)
d_weights.append(np.empty((hidden_dim,input_dim)))
w_kj = np.random.uniform(-0.3,0.3,(output_dim,hidden_dim))
weights.append(w_kj)
d_weights.append(np.empty((output_dim,hidden_dim)))

b_j = np.ones((hidden_dim,1))
biases.append(b_j)
d_biases.append(np.empty((hidden_dim,1)))
b_k = np.ones((output_dim,1))
biases.append(b_k)
d_biases.append(np.empty((output_dim,1)))

act_functions = [sigmoid, sigmoid]
d_act_functions = [d_sigmoid, d_sigmoid]

#forward propagation
for l in range(len(layer_dim)):
    if l == 0:
        layers_z[l] = weights[l] @ input + biases[l]
        layers_a[l] = act_functions[l](layers_z[l])
    else:
        layers_z[l] = weights[l] @ layers_a[l-1] + biases[l]
        layers_a[l] = act_functions[l](layers_z[l])


In [12]:
for i,a in enumerate(layers_a):
    print(f'Layer {i}')
    print(a.shape)

Layer 0
(8, 100)
Layer 1
(3, 100)


In [13]:
deltas = []
deltas.append(np.empty((hidden_dim,N)))
deltas.append(np.empty((output_dim,N)))
#backpropagation
for l in range(len(layer_dim)-1,-1,-1):
    if l == len(layer_dim)-1:
        deltas[l] = 2*d_act_functions[l](layers_z[l])*(layers_a[l]-y)
    else:
        deltas[l] = weights[l+1].T @ deltas[l+1]

for i in range(len(d_weights)):
    if i == 0:
        d_weights[i] = deltas[i] @ input.T
    else: 
        d_weights[i] = deltas[i] @ layers_a[i-1].T

print(d_weights[0])
print(d_weights[1].shape)

[[ 1.67689876  1.76818167  1.73860926  2.05389029  1.59689574]
 [-0.45594775 -0.75782144 -0.38195253 -0.84082482 -0.26670657]
 [ 0.74369032  0.62069796  0.85378303  0.65032114  0.87043844]
 [-1.53860947 -1.88154319 -1.54227131 -2.04571599 -1.378     ]
 [ 2.13506102  2.19674055  2.28474158  2.38795856  2.18191644]
 [-0.43599989 -0.4573967  -0.41259936 -0.66117457 -0.32919073]
 [ 1.42056247  1.56919431  1.44434125  1.82914517  1.29851659]
 [-0.75394905 -0.95175188 -0.71680472 -1.12680001 -0.59379996]]
(3, 8)


In [5]:
layers_a[1]-y

array([[ 0.99627385,  0.99768947,  0.99777273, -0.00249981,  0.99732848,
         0.99674436, -0.00218962,  0.99702821,  0.99768665,  0.99759335],
       [-0.00438532,  0.99732753, -0.00262682, -0.00297894, -0.00307943,
         0.99605217,  0.99745861, -0.00350356, -0.00273181,  0.99716878],
       [ 0.97736136,  0.98308885,  0.98333755, -0.0177775 ,  0.98162346,
        -0.02092771,  0.98366243,  0.98004573, -0.01702208, -0.01744107]])

In [6]:
#weight update
for i,w in enumerate(weights):
    d_weights

In [43]:
l = 0
k = 0
a = weights[l+1].T @ (act_functions[l+1](layers_z[l+1]) * (2*(layers_a[l+1]-y)))
a.shape

(8, 10)

In [35]:
(weights[l+1][k].T).shape

(8,)

In [30]:
(act_functions[l+1](layers_z[l+1][k])).shape

(10,)

In [33]:
(2*(layers_a[l+1][k]-y[k])).shape

(3,)

In [39]:
a = np.array([1,2,3]).reshape((3,1))
b = np.array([1,2,3,4]).reshape((1,4))
a @ b

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [45]:
for i,a in enumerate(layers_a):
    print(f'Layer {i}')
    print(a.shape)

Layer 0
(8, 1)
Layer 1
(3, 1)


In [7]:

#backpropagation
for l in range(len(layer_dim)-1,-1,-1):
    if l == len(layer_dim)-1:
                                #kxN                    #kxN
        delta_k = 2*act_functions[l](layers_z[l])*(layers_a[l]-y)
    else:
        tmp = 0
        for k in range(layer_dim[l+1]):
                    #1xj                                #1xN
            tmp += weights[l+1][k,:].T @ (act_functions[l+1](layers_z[l+1][k,:]) * (2*(layers_a[l+1][k,:]-y[k,:])))
        delta_j = act_functions[l](layers_z[l])*tmp

print(delta_k.shape)
print(delta_j.shape)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 10 is different from 8)