In [2]:
import numpy as np
from matplotlib import pyplot as plt
import torch
import pandas

In [ ]:
def f_act_out(x):
    '''Linear activation function'''
    return x

def f_act_hidden(x):
    '''Sigmoid activation function'''
    return 1/(1+np.exp(-x))

class NeuralNetwork():
    def __init__(self, input, hidden_units, output_units):
        self.input = input
        self.hidden = np.random.random((hidden_units, input.shape[1]))
        self.output = np.random.random((output_units, input.shape[1]))
        self.w_ji = np.random.random((hidden_units, input.shape[0]))
        self.bias_ji = np.random.random((hidden_units, 1))
        self.w_kj = np.random.random((output_units, hidden_units))
        self.bias_kj = np.random.random((output_units, 1))
        #Da mettere i bias
        #Possiamo anche mettere un 1 in capo al vettore input e il bias contarlo nella matrice w.

    def forward_prop(self):

        self.hidden = f_act_hidden(self.w_ji @ self.input + self.bias_ji)  # hidden x N
        self.output = f_act_out(self.w_kj @ self.hidden + self.bias_kj) #+ bias #output x N
    
    def backward_prop(self):
        
        delta_k = (self.output - self.target) * np.gradient(self.output)[1] # output x N
        delta_j = np.sum(delta_k @ self.w_kj)
        Dw_kj = delta_k @ self.hidden.T # output x N @ N x hidden = output x hidden 



In [2]:
N = 100 #dimensione pattern
dim_input = 5 #dimensione input
dim_hl = 3 #dimensione hidden layer
dim_ol = 2 #dimensione output layer

input = np.ones((dim_input,N))
target = np.ones((dim_ol,N))

w_ji = np.ones((dim_hl, dim_input))
w_kj = np.ones((dim_ol, dim_hl))

hidden = np.ones((dim_hl,N))
output = np.ones((dim_ol,N))

def f_act_out(x):
    '''Linear activation function'''
    return x

def f_act_hidden(x):
    '''Sigmoid activation function'''
    return 1/(1+np.exp(-x))

#Forward computation
hidden = f_act_hidden(w_ji @ input)
output = f_act_out(w_kj @ hidden)
print(output.shape)
#print(output)


(2, 100)


In [8]:
a = np.array([[1,2,3,4,5,6],[1,4,9,16,25,36]])
print(a.shape)
np.gradient(a)

(2, 6)


[array([[ 0.,  2.,  6., 12., 20., 30.],
        [ 0.,  2.,  6., 12., 20., 30.]]),
 array([[ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 3.,  4.,  6.,  8., 10., 11.]])]

In [5]:
np.array(np.gradient(output))[1]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [4]:
#Computation of errors at output layer
#print(np.array(np.gradient(output)))
delta_k = (-output+target) * (output)
print(delta_k.shape)
Dw_kj = delta_k @ hidden.T
delta_j = (w_kj.T @ delta_k) * hidden #delta_j deve essere N x input 
Dw_ji = delta_j @ input.T
print(Dw_ji.shape)
print(w_ji.shape)

(2, 100)
(3, 5)
(3, 5)


In [15]:
w_kj.shape

(2, 3)

In [ ]:
def forward_propagation()

In [ ]:
class Layer():
    def __init__(units, act_function):
        self.units = units
        self.act_function = act_function

        self.layer = np.empty((units, 1))
    
    def update_w(Dw)

class NeuralNetwork(Layer):
    def __init__(self, input, hidden_units, output_units):
        self.input = input
        self.hidden = np.random.random((hidden_units, input.shape[1]))
        #self.hidden = Layer(hidden_units, act_function)
        self.output = np.random.random((output_units, input.shape[1]))
        #self.output = Layer(output_units, act_function)

        self.w_ji = np.random.random((hidden_units, input.shape[0]))
        self.bias_ji = np.random.random((hidden_units, 1))

        self.w_kj = np.random.random((output_units, hidden_units))
        self.bias_kj = np.random.random((output_units, 1))
        
        #Da mettere i bias
        #Possiamo anche mettere un 1 in capo al vettore input e il bias contarlo nella matrice w.

    def forward_prop(self):

        self.hidden = f_act_hidden(self.w_ji @ self.input + self.bias_ji)  # hidden x N
        self.output = f_act_out(self.w_kj @ self.hidden + self.bias_kj) #+ bias #output x N
    
    def backward_prop(self):
        
        delta_k = (self.output - self.target) * np.gradient(self.output)[1] # output x N
        delta_j = np.sum(delta_k @ self.w_kj)
        Dw_kj = delta_k @ self.hidden.T # output x N @ N x hidden = output x hidden 


In [36]:
def linear(x):
    '''Linear activation function'''
    return x

def sigmoid(x):
    '''Sigmoid activation function'''
    return 1/(1+np.exp(-x))

def d_sigmoid(x):
    return sigmoid(x)*(1-sigmoid(x))

layers_a = []
layers_z = []
weights = []
biases = []

d_weights = []
d_biases = []

N = 100 #batch dimension
input_dim = 5 
hidden_dim = 8
output_dim = 3
layer_dim = [hidden_dim, output_dim]

for i in range(len(layer_dim)):
    layers_a.append(np.empty((layer_dim[i],N)))
    layers_z.append(np.empty((layer_dim[i],N)))

input = np.random.random((input_dim,N))
y = np.random.randint(0,2,(output_dim,N))

w_ji = np.random.uniform(-0.3,0.3,(hidden_dim,input_dim))
weights.append(w_ji)
d_weights.append(np.empty((hidden_dim,input_dim)))
w_kj = np.random.uniform(-0.3,0.3,(output_dim,hidden_dim))
weights.append(w_kj)
d_weights.append(np.empty((output_dim,hidden_dim)))

b_j = np.ones((hidden_dim,1))
biases.append(b_j)
d_biases.append(np.empty((hidden_dim,1)))
b_k = np.ones((output_dim,1))
biases.append(b_k)
d_biases.append(np.empty((output_dim,1)))

act_functions = [sigmoid, sigmoid]
d_act_functions = [d_sigmoid, d_sigmoid]

#forward propagation
for l in range(len(layer_dim)):
    if l == 0:
        layers_z[l] = weights[l] @ input + biases[l]
        layers_a[l] = act_functions[l](layers_z[l])
    else:
        layers_z[l] = weights[l] @ layers_a[l-1] + biases[l]
        layers_a[l] = act_functions[l](layers_z[l])


In [37]:
for i,a in enumerate(layers_a):
    print(f'Layer {i}')
    print(a.shape)

Layer 0
(8, 100)
Layer 1
(3, 100)


In [38]:
deltas = []
deltas.append(np.empty((hidden_dim,N)))
deltas.append(np.empty((output_dim,N)))
#backpropagation
for l in range(len(layer_dim)-1,-1,-1):
    if l == len(layer_dim)-1:
        deltas[l] = 2*d_act_functions[l](layers_z[l])*(layers_a[l]-y)/y.shape[1]
    else:
        deltas[l] = weights[l+1].T @ deltas[l+1]

for i in range(len(d_weights)):
    if i == 0:
        d_weights[i] = deltas[i] @ input.T
        d_biases[i] = deltas[i].sum(axis=1).reshape((deltas[i].shape[0],1))
    else: 
        d_weights[i] = deltas[i] @ layers_a[i-1].T
        d_biases[i] = deltas[i].sum(axis=1).reshape((deltas[i].shape[0],1))

print(d_weights[0])
print(d_weights[1].shape)
print(d_biases[0].shape)
print(d_biases[1].shape)

[[ 0.00662616  0.00637228  0.00738034  0.00656117  0.00549375]
 [-0.00013578 -0.00017834 -0.00179814 -0.00084971 -0.00219556]
 [ 0.01820403  0.01612615  0.01666229  0.01376057  0.01351528]
 [-0.01185664 -0.01150553 -0.01260115 -0.01173269 -0.0087819 ]
 [-0.00868432 -0.00777199 -0.00681573 -0.00630867 -0.0047521 ]
 [ 0.02431211  0.02184938  0.02301277  0.01932113  0.01832983]
 [-0.0070048  -0.00741169 -0.0090143  -0.00881523 -0.00583896]
 [ 0.02128513  0.01959225  0.02293638  0.01893471  0.01867783]]
(3, 8)
(8, 1)
(3, 1)


In [31]:
layers_a[1]-y

array([[ 0.78905826,  0.78730059,  0.78733309,  0.78616837, -0.20993073,
        -0.21140939,  0.7859117 , -0.21303588, -0.21308077, -0.2135605 ,
        -0.2110439 ,  0.78884225, -0.21158154,  0.78646433,  0.78993787,
        -0.20897614, -0.21609959,  0.78995301,  0.78688812, -0.21136026,
        -0.21391391, -0.21243251,  0.78749986,  0.78812805, -0.2118314 ,
         0.78706355, -0.21128195, -0.2084679 , -0.21369724,  0.78788733,
        -0.21316653,  0.7896671 , -0.21333439, -0.21049669,  0.79088574,
        -0.21172429, -0.21243227, -0.20843329, -0.21146457,  0.78660247,
         0.78800862, -0.21007861, -0.2141437 , -0.21124813,  0.78869404,
         0.78656868, -0.21280227,  0.78493183,  0.7842638 , -0.21332867,
         0.78793858, -0.21308368,  0.78754794,  0.78531495, -0.21404935,
        -0.21315808,  0.78590645, -0.21325774,  0.7872054 , -0.21234994,
        -0.2098902 ,  0.78481456,  0.78308358, -0.21308017, -0.2116251 ,
        -0.21313975, -0.21323762, -0.21489639, -0.2

In [39]:
#weight update
eta = 0.1
for i in range(len(weights)):
    weights[i] = weights[i] - d_weights[i]*eta
    biases[i] = biases[i] - d_biases[i]*eta
    print(weights[i].shape)
    print(biases[i].shape)




(8, 5)
(8, 1)
(3, 8)
(3, 1)


In [3]:
def linear(x):
    '''Linear activation function'''
    return x

def sigmoid(x):
    '''Sigmoid activation function'''
    return 1/(1+np.exp(-x))

def d_sigmoid(x):
    return sigmoid(x)*(1-sigmoid(x))

layers_a = []
layers_z = []
weights = []
biases = []

d_weights = []
d_biases = []

N = 100 #batch dimension
input_dim = 5 
hidden_dim = 8
output_dim = 3
layer_dim = [hidden_dim, output_dim]

for i in range(len(layer_dim)):
    layers_a.append(np.empty((layer_dim[i],N)))
    layers_z.append(np.empty((layer_dim[i],N)))

input = np.random.random((input_dim,N))
y = np.random.randint(0,2,(output_dim,N))

w_ji = np.random.uniform(-0.3,0.3,(hidden_dim,input_dim))
weights.append(w_ji)
d_weights.append(np.empty((hidden_dim,input_dim)))
w_kj = np.random.uniform(-0.3,0.3,(output_dim,hidden_dim))
weights.append(w_kj)
d_weights.append(np.empty((output_dim,hidden_dim)))

b_j = np.ones((hidden_dim,1))
biases.append(b_j)
d_biases.append(np.empty((hidden_dim,1)))
b_k = np.ones((output_dim,1))
biases.append(b_k)
d_biases.append(np.empty((output_dim,1)))

act_functions = [sigmoid, sigmoid]
d_act_functions = [d_sigmoid, d_sigmoid]

In [ ]:

o = 0
while o<1000:
    print(f'o = {o}')
    #forward propagation
    for l in range(len(layer_dim)):
        if l == 0:
            layers_z[l] = weights[l] @ input + biases[l]
            layers_a[l] = act_functions[l](layers_z[l])
        else:
            layers_z[l] = weights[l] @ layers_a[l-1] + biases[l]
            layers_a[l] = act_functions[l](layers_z[l])

    deltas = []
    deltas.append(np.empty((hidden_dim,N)))
    deltas.append(np.empty((output_dim,N)))
    #backpropagation
    for l in range(len(layer_dim)-1,-1,-1):
        if l == len(layer_dim)-1:
            deltas[l] = 2*d_act_functions[l](layers_z[l])*(layers_a[l]-y)/y.shape[1]
        else:
            deltas[l] = weights[l+1].T @ deltas[l+1]

    for i in range(len(d_weights)):
        if i == 0:
            d_weights[i] = deltas[i] @ input.T
            d_biases[i] = deltas[i].sum(axis=1).reshape((deltas[i].shape[0],1))
        else: 
            d_weights[i] = deltas[i] @ layers_a[i-1].T
            d_biases[i] = deltas[i].sum(axis=1).reshape((deltas[i].shape[0],1))

    print(d_weights[0])
    print(d_weights[1].shape)
    print(d_biases[0].shape)
    print(d_biases[1].shape)
    #weight update
    eta = 0.1
    for i in range(len(weights)):
        weights[i] = weights[i] - d_weights[i]*eta
        biases[i] = biases[i] - d_biases[i]*eta

    o += 1

In [4]:
import numpy as np
import math


#linear activation function 
def linear(x):
    return x

def d_linear(x):
    return 1

#sigmoid activation function
def sigmoid(x):
    return 1/(1+np.exp(-x))

def d_sigmoid(x):
    f =sigmoid(x)
    return f * (1-f)

#ReLu activation function
def relu(x):
    return np.max(0,x)

def d_relu(x):
    return int(x>0)

#hyperbolic tangent activation function
def TanH(x):
    return np.tanh(x)

def d_TanH(x):
    return 1 - math.pow(np.tanh(x), 2) 

#Dictionary for the activation functions
act_func = {
    'lin': linear,
    'sigm': sigmoid,
    'relu': relu,
    'tanh': TanH
}

#A second dictionary for their derivatives
d_act_func = {
    'lin': d_linear,
    'sigm': d_sigmoid,
    'relu': d_relu,
    'tanh': d_TanH
}

In [1]:
class Layer:

    def __init__(self, input, prev_layer, dim_layer, act_function, dim_batch, target):

        self.dim_layer = dim_layer
        self.prev_layer = prev_layer
        self.act_function = act_func[act_function]
        self.d_act_function = d_act_func[act_function]
        self.dim_batch = dim_batch
        self.target = target

        if self.prev_layer != None:
            self.W = np.random.uniform(-0.2, 0.2, (self.dim_layer, self.prev_layer.dim_layer))    #inizializzo la matrice dei pesi
            self.b = np.random.uniform(-0.2, 0.2, (self.dim_layer, self.dim_batch))      #inizializzo il vettore dei bias
            self.layer = np.empty((self.dim_layer, self.dim_batch))
        else: 
            self.layer = input

    def forward(self):
        if self.prev_layer == None:
            print('prev_layer == None: return self.layer')
            return self.layer
        else: 
            print('prev_layer =! None: compute forward')
            self.z = self.W @ self.prev_layer.forward() + self.b
            self.layer = self.act_function(self.z)
            return self.layer
    
    def backward(self, next_delta, next_weights):
        print(f'Entered backward: target = {self.target}')
        
        if self.target is None:
            if self.prev_layer != None:
                print('self.target == None: hidden')
                delta = next_weights.T @ next_delta
                #self.prev_layer.backward(delta,self.weights)
                self.d_W = delta @ self.prev_layer.backward(delta,self.W).T
                self.d_b = delta.sum(axis=1).reshape((delta.shape[0],1))
                return self.layer

            else: 
                print('input')
                return self.layer
            
        else:
            print('self.target != None: output')
            delta = 2 * self.d_act_function(self.z) * (self.layer - self.target)/self.target.shape[1]
            #self.prev_layer.backward(delta,self.weights)
            self.d_W = delta @ self.prev_layer.backward(delta,self.W).T
            self.d_b = delta.sum(axis=1).reshape((delta.shape[0],1))
            return self.layer    

    def update_weights(self, eta):
        if self.prev_layer is None:
            return
        else:  
            self.W = self.W - eta * self.d_W
            self.prev_layer.update_weights(eta)


In [2]:
input_layer = Layer(input, None, 5, 'lin', 100, None)
hidden_layer = Layer(None, input_layer, 8, 'sigm', 100, None)
output_layer = Layer(None, hidden_layer, 3, 'sigm', 100, y)

NameError: name 'act_func' is not defined

In [61]:
output_layer.forward()

prev_layer =! None: compute forward
prev_layer =! None: compute forward
prev_layer == None: return self.layer


array([[0.55308483, 0.57060642, 0.57127585, 0.51116767, 0.51429673,
        0.58918799, 0.5320979 , 0.52437182, 0.55960736, 0.53453741,
        0.52303894, 0.52668929, 0.52469992, 0.50985699, 0.53433008,
        0.52463116, 0.58410699, 0.58704386, 0.53038132, 0.52614839,
        0.60276981, 0.58672433, 0.60066383, 0.51600162, 0.54748058,
        0.58215144, 0.5860736 , 0.52325247, 0.57896977, 0.52504101,
        0.57153595, 0.57628479, 0.56737654, 0.53191928, 0.5990363 ,
        0.57311031, 0.59301413, 0.58961265, 0.50747044, 0.57886493,
        0.54382195, 0.60183189, 0.58733892, 0.54705752, 0.55410878,
        0.54019972, 0.51146949, 0.57068685, 0.51167995, 0.58144989,
        0.53680763, 0.55732031, 0.54038827, 0.52528295, 0.59493734,
        0.56915354, 0.57106836, 0.50627798, 0.56302076, 0.59119437,
        0.57284544, 0.51462158, 0.54218939, 0.51170172, 0.56226095,
        0.60202234, 0.51787829, 0.5309385 , 0.54878633, 0.55744983,
        0.60680293, 0.53240159, 0.59568601, 0.51

In [62]:
output_layer.backward(None, None)

Entered backward: target = [[1 0 1 0 0 1 0 0 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0 1
  1 0 1 1 1 0 1 0 0 1 0 0 1 0 1 0 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 0 0 1 0 1
  0 1 1 0 0 1 1 1 0 1 1 0 0 0 0 1 1 1 0 1 0 0 0 0 1 1 1 0]
 [0 1 0 0 0 1 0 0 1 1 1 1 1 1 1 0 1 1 0 1 0 0 0 1 1 1 0 1 1 0 0 0 0 0 1 0
  1 0 0 1 1 0 0 1 1 1 1 1 0 1 0 1 0 0 0 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 1
  1 1 1 0 1 1 0 1 1 1 0 0 1 0 1 1 0 1 0 1 1 0 0 1 1 0 0 1]
 [1 0 0 1 1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 1 1 1 1 0 1 0 0 1 0 0 1 1 1 1 1 1
  0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 1 0 1 0 0
  0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 1]]
self.target != None: output
Entered backward: target = None
self.target == None: hidden
Entered backward: target = None
input


array([[0.55308483, 0.57060642, 0.57127585, 0.51116767, 0.51429673,
        0.58918799, 0.5320979 , 0.52437182, 0.55960736, 0.53453741,
        0.52303894, 0.52668929, 0.52469992, 0.50985699, 0.53433008,
        0.52463116, 0.58410699, 0.58704386, 0.53038132, 0.52614839,
        0.60276981, 0.58672433, 0.60066383, 0.51600162, 0.54748058,
        0.58215144, 0.5860736 , 0.52325247, 0.57896977, 0.52504101,
        0.57153595, 0.57628479, 0.56737654, 0.53191928, 0.5990363 ,
        0.57311031, 0.59301413, 0.58961265, 0.50747044, 0.57886493,
        0.54382195, 0.60183189, 0.58733892, 0.54705752, 0.55410878,
        0.54019972, 0.51146949, 0.57068685, 0.51167995, 0.58144989,
        0.53680763, 0.55732031, 0.54038827, 0.52528295, 0.59493734,
        0.56915354, 0.57106836, 0.50627798, 0.56302076, 0.59119437,
        0.57284544, 0.51462158, 0.54218939, 0.51170172, 0.56226095,
        0.60202234, 0.51787829, 0.5309385 , 0.54878633, 0.55744983,
        0.60680293, 0.53240159, 0.59568601, 0.51