In [1]:
import numpy as np
from matplotlib import pyplot as plt
from NeuralNetwork import NeuralNetwork
from utils import get_data, onehot_encoding, grid_search, save_dict_to_file, load_dict_from_file
from Layer import Layer, Input
from functions import accuracy, MSE, MEE
import pandas as pd

In [2]:
np.random.seed(42)

In [3]:
input_layer = Input(5)
hidden_layer = Layer(input_layer, 10, 'sigm')
output_layer = Layer(hidden_layer, 3, 'lin')

In [4]:
hidden_layer.W

array([[-0.12545988,  0.45071431,  0.23199394,  0.09865848, -0.34398136],
       [-0.34400548, -0.44191639,  0.36617615,  0.10111501,  0.20807258],
       [-0.47941551,  0.46990985,  0.33244264, -0.28766089, -0.31817503],
       [-0.31659549, -0.19575776,  0.02475643, -0.06805498, -0.20877086],
       [ 0.11185289, -0.36050614, -0.20785535, -0.13363816, -0.04393002],
       [ 0.28517596, -0.30032622,  0.01423444,  0.09241457, -0.45354959],
       [ 0.10754485, -0.32947588, -0.43494841,  0.44888554,  0.46563203],
       [ 0.30839735, -0.19538623, -0.40232789,  0.18423303, -0.05984751],
       [-0.37796177, -0.00482309, -0.46561148,  0.4093204 , -0.24122002],
       [ 0.16252228, -0.18828892,  0.02006802,  0.04671028, -0.31514554]])

In [5]:
output_layer.W

array([[-0.11132271, -0.22865097,  0.32873751, -0.14324667, -0.21906549,
         0.04269608, -0.35907578,  0.30219698, -0.42544936,  0.48688694],
       [ 0.27224477, -0.30128432, -0.49447788,  0.31546143,  0.20685734,
         0.22900717,  0.27127035, -0.42595535, -0.14153427, -0.38413094],
       [ 0.36310343,  0.12329813, -0.16910198, -0.43644165, -0.18901768,
        -0.17481668,  0.22960618,  0.13755747,  0.38721274, -0.02778507]])

In [6]:
input_layer2 = Input(5)
hidden_layer2 = Layer(input_layer2, 10, 'sigm')
output_layer2 = Layer(hidden_layer2, 3, 'lin')

In [7]:
hidden_layer2.W

array([[ 0.0612772 ,  0.27096718, -0.0062044 ,  0.02273283, -0.07245898],
       [-0.47458087, -0.39210857, -0.46857081,  0.13641041, -0.18564402],
       [ 0.00857069,  0.40756647, -0.25070777, -0.08961708,  0.25555114],
       [-0.27120183, -0.42302009, -0.21024855, -0.33877871,  0.42969765],
       [ 0.30812038,  0.13340376,  0.37146059,  0.30367208, -0.31342994],
       [ 0.392559  ,  0.03934224,  0.30744016,  0.3960913 , -0.18199653],
       [-0.38994808, -0.27206484, -0.07289221,  0.31801477,  0.36073058],
       [-0.49304787,  0.0107473 , -0.082589  , -0.27789219, -0.38013463],
       [-0.16238483,  0.4429097 , -0.17679707,  0.01879062,  0.20301896],
       [-0.1363704 ,  0.47178208,  0.46244729, -0.2482177 , -0.00275149]])

In [8]:
output_layer2.W

array([[-0.01054724,  0.48565045, -0.25794473,  0.17213555,  0.26161962,
        -0.26236246,  0.22821635, -0.13221687,  0.13230583,  0.13352971],
       [ 0.03577468, -0.40971023,  0.3353025 , -0.17921994, -0.31348149,
        -0.45922486,  0.09089294,  0.17756436, -0.48341217,  0.01209306],
       [-0.27350422,  0.14517279, -0.32563357,  0.19093774, -0.11326465,
         0.43672999, -0.36247906, -0.15893365, -0.38652648,  0.42469362]])